import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionManager from "../components/SessionManager/SessionManager";
import { SpotifyProvider } from "../context/SpotifyContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Spotify", 
  description: "Generated by create next app", 
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
        <SpotifyProvider>
          <SessionManager>
            {children}
          </SessionManager>
        </SpotifyProvider>
      </body>
    </html>
  );
}
